# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e85df720b236cb046bfa6e8d4019b54211e83b783ce362264a942a3c9989005885c501bc408077e312ea3c6c1cde20742af82266a9543c40016c2b1077817a6

test:
  secret_key_base: e623e7bb0b15b85f60e3541077601292309f0f59880e8fc0fe2db4b0e835d8f4303b1520f816b99471de725b3a2fdc7dd7a7005a4bd1ced9ce9bee68bb07336e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
